import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Router from 'next/router'
import { prisma } from '../lib/prisma.js';
import { GetServerSideProps } from 'next';
import HeaderCompanyOptions from '../components/HeaderCompanyOptions';


export const getStaticProps = async () => {
  if (prisma === null) {
    return null
  }

  const companies = await prisma.company.findMany(
    {where: { published: true },
     include: {
      founders: {
        select: {
          name: true,
          grad_year: true,
          url: true,
          email: true,
        },
      },
      funding_stage: {
        select: {
          name: true,
        },
      },
     },
     } );
  companies.map((item) => {
    if (item.createdAt !== null) {
      item.createdAt = item.createdAt.toString();
    }
  });

  return { props: { companies } };
};


export default function Home(props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>HoosBuilding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.splash}>
          <div className={styles.splashContent}>
            <div className={styles.left}>
              <h1 className={styles.tagline}>The largest community of student builders at the University of Virginia.</h1>
              <p className={styles.desc}>We’re bringing together the best and brightest builders in Charlottesville. Members have access to exclusive yada yada yada blah blah blah words etc. etc.</p>
              <div className={styles.interestedContainer}>
                <div className={styles.interested} onClick={() => console.log("Im interested clicked")}>I'm interested</div>
              </div>
            </div>
            <HeaderCompanyOptions />
          </div>
        </div>
        <div className={styles.companyCards}>
          {props.companies.map((company) => (
            <div key={company.id} className={styles.companyOuterCard}>
              <div className={styles.companyInnerCard}>
                <p className={styles.companyName}>{company.name}</p>
                <div className={styles.companySubtitle}>
                  {company.founding_year},{' '}
                  {company.founders.map((founder) => (
                    <p className={styles.companyFounder}>{founder.name} ('{founder.grad_year.slice(-2)})</p>
                  ))}
                </div>
                <p className={styles.fundingStage}>{company.funding_stage.name}</p>
                <p className={styles.description}>{company.description}</p>
              </div>
            </div>
          ))}
        </div>
      </main>

      <p className={styles.myFooter}>
          Managed by v1 Virginia, Inspired by GSBuilds
      </p>
    </div>
  )
}
